### ISSUE TITLE
what can libcrossaudio do?

### ISSUE THREAD

**Issue by JonnycatMeow** [mumble-voip/libcrossaudio#2]
i am just wondering what it does?

**Comment by davidebeatrici** [comment]
Right now not much because it's in early development stages.

Once deemed usable, it will be used in Mumble to replace the audio backend interfaces.

The library will basically provide a unified interface for all backends (PipeWire, WASAPI, CoreAudio, etc.), while attempting to maintain high-performance and flexibility.

**Comment by luzpaz** [comment]
Any updates here ?

**Comment by Krzmbrzl** [comment]
The intended use is still the same, but development has not progressed too far yet.

**Comment by mirh** [comment]
Mumble is certainly on the forefront of speedy solid audio (and I can see why it may have different priorities than other programs).
But how does this specifically compare to JACK, portaudio or cubeb?

**Comment by Krzmbrzl** [comment]
I think the question on how libcrossaudio compares to audio backend x doesn't really make sense since this library is a cross-platform wrapper for the various audio backends on different systems (that unifies their APIs). 

Therefore it simply uses Jack, PulseAudio, etc. under the hood.

**Comment by mirh** [comment]
I mean.. Even the others are cross-platform wrappers for the whatever the actual OS apis are (JACK is only native on linux btw).
Unless you meant that libcrossaudio is like a wrapper of wrappers, but it seems strange (especially considering that AFAIK mumble is pretty fairly native on every platform now)

**Comment by Krzmbrzl** [comment]
> Unless you meant that libcrossaudio is like a wrapper of wrappers

I did. It provides a unified API of all these different backends in order to allow audio related stuff to be programmed once and then work with whatever is installed on a given computer. 

Mumble is "native" on most systems because it essentially contains something like libcrossaudio in its sources. This library is meant to pull this outside into a dedicated library that is reusable and completely separated from other Mumble source code (to remove interdepencies) in order to improve maintainability.

**Comment by davidebeatrici** [comment]
I think @mirh's question was whether we rely on already existing wrappers.

We don't, we interact directly with the backends we support.

**Comment by mirh** [comment]
Yes, indeed. So in this sense, it ***is*** an alternative for all the libraries/wrappers I mentioned in the first step (*native linux JACK aside). 

And I can imagine cubeb is perhaps massive and overcomplicated, while portaudio is very polyvalent but it has its own legacy idiot balls.. But they are just uneducated guesses and I wanted to hear from you.

**Comment by JonnycatMeow** [comment]
alright I'ma close this issue
